### ISSUE TITLE
got error when training

### ISSUE THREAD

**Issue by HandsomeHans** [lyakaap/Kaggle-Carvana-3rd-Place-Solution#1]
I am new to Keras. After learning some tutorial on the internet, I tried to train. But always got a problem. 

**my training code is:**

`train_datagen = image.ImageDataGenerator(
        rotation_range=40,
        width_shift_range=0.2,
        height_shift_range=0.2,
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True,
        fill_mode='nearest')
        
val_datagen = image.ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory('../images/train/cat/',
                                                    target_size=(1920,1280),
                                                    batch_size=32,
                                                    class_mode='binary')

val_generator = val_datagen.flow_from_directory('../images/val/cat/',
                                                target_size=(1920,1280),
                                                batch_size=8,
                                                class_mode='binary')

model.fit_generator(
        train_generator,
        steps_per_epoch=11250//32,
        epochs=10,
        validation_data=val_generator,
        validation_steps=144)

model.save_weights('../models/pet.h5')`

**and the error is:**

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/hans/Kaggle/Fine-Grained/doc/fine-grained.py", line 98, in <module>
    validation_steps=144)

  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2042, in fit_generator
    class_weight=class_weight)

  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1762, in train_on_batch
    outputs = self.train_function(ins)

  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2273, in __call__
    **self.session_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 961, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))

ValueError: Cannot feed value of shape (32, 1) for Tensor u'conv2d_22_target:0', which has shape '(?, ?, ?, ?)'`

**Comment by HandsomeHans** [comment]
I think the problem could be the input dimension, input_shape is (1920, 1280, 3).

**Comment by HandsomeHans** [comment]
I got a big fault. This net outputs a gray image instead of an index or accuracy or something else. And input should be one image.
